models:
  image: tp33/django
  container_name: web
  external_links:
    - mysql:db
  volumes:
    - ~ :/app
  ports:
    - "8001:8000"
  command: bash -c "cd /app/myweb && python manage.py makemigrations myapp && python manage.py migrate && python manage.py loaddata data.json && mod_wsgi-express start-server --working-directory /app/myweb --reload-on-changes /app/myweb/myweb/wsgi.py"

