# Generated by Django 2.1 on 2018-11-01 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0002_auto_20181101_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authenticator',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modelapp.User'),
        ),
    ]
